### ISSUE TITLE
Linux version doesn't instantiate in Bitwig 1.3.11

### ISSUE THREAD

**Issue by davephillips** [jd-13/Carve-Distortion#6]
Build from latest git pull proceeds without problems, but the resulting plugin fails to load in Bitwig 1.3.11 or in the latest Ardour5 (beta from git sources). Alas, the only error reported by BW by default is this:

com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: Could not read VST plug-in metadata
64 bit plugin host reported errors: Pluginhost returned non zero exit code 255

32 bit plugin host reported errors: Pluginhost returned non zero exit code 255

A5 reports nothing at all. Not very helpful, I know. Please advise if there's a better way to debug the issue (gdb maybe?).

**Comment by jd-13** [comment]
Hi, 

Am I correct in assuming you are building for Linux? I haven't so far been able to replicate this, so I think it could be a part of your build process that is causing this.

Could you let me know which compiler you are using, and (assuming you are using the Projucer to generate the makefile) check all fields are populated in the project settings:
<img width="647" alt="carveprojectsettings" src="https://cloud.githubusercontent.com/assets/9828525/16895119/f946f386-4b62-11e6-9885-939b7d6972bd.png">
Though many of those settings are only used for AudioUnits, I believe some could potentially cause issues for VSTs if they are missing.

Also if possible, could you see if the issue is still present when using the linux build available from the website: https://whiteelephantaudio.com/plugins/carve/

**Comment by davephillips** [comment]
Thanks for the tips, I set up my build with your suggested settings, but alas, I still can't get the plugin to instantiate in BW 1.3.11. Ditto for the prepared binary, same problem. My older build of Richter loads without troubles, btw. Just not getting joy from Carve or MONSTR. I'm happy to test further, so feel free to make any suggestions. Btw, I am using the Projucer from JUCE 4.2.1 with GCC 4.9.2 on Fedora 21 x86_64.

**Comment by davephillips** [comment]
Update: I found the error in my system. libDSPFilters.so was not located in /usr/lib64/ so I symlinked it from /usr/local/lib, ran lddconfig, and voila, I have a running Carve VST plugin in BW 1.3.11. However, the prepared binary fails with a versioning error (GLIBCXX 4.3.2 required for libstdc++). Anyway, I can test it now. I'll retry MONSTR and see it goes.

**Comment by jd-13** [comment]
Good to hear you now have your build working. Regarding the downloadable binary, could you post the output of the following on your system? It appears that the version of glibc that you have may be different to what I used to build the binary.


strings /usr/lib/libstdc++.so.6 | grep LIBCXX


ls -l /usr/lib/libstdc++.so.6
