### ISSUE TITLE
Any build instructions?

### ISSUE THREAD

**Issue by erikd** [jd-13/Carve-Distortion#8]
Would be really nice to have simple step-by-step build instructions in the Readme.

**Comment by jd-13** [comment]
Hi, in future I might add some detailed build instructions, but for now the following should work:

If you're familiar with JUCE and the Projucer you should be able to build the project by creating an audio plugin project in the Projucer, and replacing the auto generated files with the source files from this repo (not including the tests directory). I'd recommend using the dev branch of this repo for building, as the master branch is only updated with each release so may not build with the latest WE-Core.

The WE-Core and DSPFilters libraries (linked in the README) will need to be added to the header search paths, and the DSPFilters *.cpp implementation files may need to be added to the project alongside the source from this repo.

I think that's everything but I may have missed something since I'm just writing this from memory, feel free to let me know if you have any issues.

**Comment by erikd** [comment]
Unforrtunately I am totally unfamiliar with JUCE and Projucer. I'm a a Linux dev who hasn't done any native Windows development in over 10 years.

**Comment by jd-13** [comment]
In that case I'll add some proper build instructions using the Projucer when I've got time, as that is the easiest way to build the project for most any OS (including Linux).

The reason I don't simply include a makefile for this project is that I use the Projucer to manage the build settings for all platforms I build on (windows, mac, and linux) and for Linux it generates a makefile which relies on the library paths and settings on my system, so would require some tweaking to work elsewhere. I may attempt to change this so that the makefile is more portable and worth adding to the repo.

**Comment by erikd** [comment]
Proper build instructions would be awesome, but if you could just throw the geneated Makefile up on a gist that would be immensely helpful and get me started immediately.

**Comment by jd-13** [comment]
Sorry this took a little while, I've been trying to setup the makefile in a way that would be useful, but it relies on a lot of .h and .cpp files that are auto generated by the Projucer. I've now added instructions for building using the Projucer in the dev branch readme: https://github.com/jd-13/Carve-Distortion/blob/dev/README.md

**Comment by erikd** [comment]
Thanks!
